config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'shop#index'

  resources :products do
    member do
      post :agree
    end
  end

  resources :contracts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :contracts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def index
    @contracts = current_user.contracts
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:mode] == "owned"
      @products = current_user.products
    elsif params[:mode] == "offers"
      @products = Product.where.not(user: current_user)
    else
      @products = Product.all
    end
  end

  def new
    @product = Product.new
  end

  def create 
    @product = Product.new(prod_params)
    if @product.save
      redirect_to products_path
    else 
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_path, notice: "Product Removed!"
    end
  end

  def agree
    current_user.contracts.create(
      product_id: params[:id]
    )
    redirect_to products_path, notice: "Product Accepted"
  end

  private

  def set_prod
    @product = Product.find(params[:id])
  end

  def prod_params
    params.require(:product).permit(:name, :status, :price, :user_id)
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def user_action(product)
    if product.user == current_user
      link_to 'Delete', product_path(product), method: :delete
    else
      link_to 'Agree', agree_product_path(product), method: :post
    end
  end

  def header
    if params[:mode] == "owned"
      "My products"
    elsif params[:mode] == "offers"
      "Offers"
    end
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contracts/index.html.erb
<h1>Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product price</th>
      <th>Contract date</th>
    </tr>
  </thead>
  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.product.name %></td>
        <td><%= contract.product.price %></td>
        <td><%= contract.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donsaturday</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= current_user.name %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% end %>

    <%= render 'shared/menu' %>
    <%= yield %>
        <td></td>
  </body>
</html>

app/views/products/index.html.erb
<h1><%= header %></h1>

<%= link_to 'Add product', new_product_path %>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Status</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.status? ? "" : "pending" %></td>
        <td>₱<%= product.price %></td>
        <td><%= user_action(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="container">
  <h1>Fill out the form</h1>

    <%= form_for @product do |f| %>
      <div class="field">
        Product name<br />
        <%= f.text_field :name, placeholder: "1 hectare lot", required: true, autofocus: true, class:"form-control" %>
      </div><br />

      <div class="field">
        <%# Product status<br /> %>
        <%= f.text_field :status, type: :hidden %>
      </div>

      <div class="field">
        Manufacturer's Suggested Retail Price<br />
        <%= f.text_field :price, placeholder: "₱ 1,000,000.00", required: true, class:"form-control" %>
      </div><br />

      <div class="field">
        <%# User id<br /> %>
        <%= f.number_field :user_id, value: current_user.id, type: :hidden %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div><br />
    <% end %>

  <%= link_to 'Cancel', products_path %>
</div>

app/views/shared/_menu.html.erb
<%= link_to 'My products', products_path(mode: "owned") %>
<%= link_to 'Offers', products_path(mode: "offers") %>
<%= link_to 'Contracts', contracts_path %>

app/views/shop/index.html.erb
<h1>Homepage</h1>

<%= link_to 'See all products', products_path %>